### ISSUE TITLE
object.size much larger with v1.2

### ISSUE THREAD

**Issue by tim-salabim** [SymbolixAU/geojsonsf#45]
I just updated to version 1.2 and notice quite some increase in the object size after conversion to geojson from sf. The following is not reproducible, but should convey the issue:

```r
library(sf)
library(geojsonsf)

fra = st_read("../_PG/PG_FR_2018.shp")
Simple feature collection with 50071 features and 38 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -5.143017 ymin: 41.33332 xmax: 9.560337 ymax: 51.08906
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
> object.size(fra)
180228320 bytes
```
with version 1.1 I see
```r
> fra_js = sf_geojson(fra)
> object.size(fra_js)
194854256 bytes
```
whereas with v 1.2
```r
> fra_js = sf_geojson(fra)
> object.size(fra_js)
299168640 bytes
```
In both cases, the object size on disk is similar to the one reported by `object.size`. 

Is this intended/unavaoidable? It would be great to try and minimise the object size, as one quickly runs into issues of 'allocation size overflow' in the browser when reading them from disk.

Btw, the speed of conversion has increased noticably (though I did not benchmark).

**Comment by SymbolixAU** [comment]
Here's a reproducible example which demonstrates your findings

```r
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"))

geo <- geojsonsf::sf_geojson( nc )

## v1.1
format( object.size( geo ), units = "Kb" )
# [1] "84.1 kb"

## v1.2
format( object.size( geo ), units = "Kb" )
# [1] "124.8 Kb"
```

This is not intentional, after all it's just a string...

**Comment by SymbolixAU** [comment]
I think it's to do with the precision. v1.2 doesn't do any rounding

Here's the last entry of the `nc` object for comparison

```r
## v1.2
# [-78.65571594238281,33.948673248291019]

## v1.1
## [-78.655716,33.948673]

## 
nc[100, 'geometry'][[1]][[1]][[1]][27, ]
# [1] -78.65572  33.94867
```

**Comment by tim-salabim** [comment]
Would a `presicion` argument make sense?

**Comment by tim-salabim** [comment]
Kinda. Not for anything on CRAN, but for [leaflet.glify](https://github.com/tim-salabim/leaflet.glify/blob/master/R/glify-polygons.R#L65) where I use it to write polygon features to disk (which are then opened in the browser via [JSON.parse](https://github.com/tim-salabim/leaflet.glify/blob/master/inst/htmlwidgets/Leaflet.glify/addGlifyPolygons.js#L32). This is where the size of the objects is critical. 

I don't wanna keep you from meeting your deadline. I could just try to make sure I round whatever comes in myself before passing it to the browser via `sf_geojson`. As for a longer term, sustainable solution, I still think a user exposed argument re precision would be best for both geojsonsf and jsonify.

**Comment by SymbolixAU** [comment]
> I still think a user exposed argument re precision would be best for both geojsonsf and jsonify

I agree, and will work towards it from November. 

Thanks again for your input.

**Comment by tim-salabim** [comment]
Thanks, there is no rush really. 

I think I can, for now, hack my way to lower precision to save space. (I am casting to "POLYGON" below as Leaflet.glify does not handle "MULTIPOLYGONS")

```r
library(sf)

nc <- st_read(system.file("shape/nc.shp", package="sf")) %>% 
  st_cast("POLYGON")

geo <- geojsonsf::sf_geojson( nc )

## v1.2
format( object.size( geo ), units = "Kb" )
# [1] "126.3 Kb"

# set precision to 6 digits
nc2 = st_set_precision(nc, 1000000) %>% 
  st_union(by_feature = TRUE) %>%
  st_cast("POLYGON")

geo2 <- geojsonsf::sf_geojson( nc2 )

## v1.2
format( object.size( geo2 ), units = "Kb" )
# [1] "86.5 Kb"
```
This operation seems acceptable in terms of speed. Takes about 3 sec. for 50k polygons. One great advantage of rounding the coordinates this way is that it will fail if the rounding produces invalid geometries.

Pinging @edzer to see whether there are smarter ways to round (multi)polygon coordinates in sf?

**Comment by SymbolixAU** [comment]
@tim-salabim there's a digits branch where I'm now getting this result

```r
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"))

geo <- geojsonsf::sf_geojson( nc )
geo2 <- geojsonsf::sf_geojson( nc, digits = 2 )

## digits = NULL
format( object.size( geo ), units = "Kb" )
# [1] "124.8 Kb"

## digits = 2
format( object.size( geo2 ), units = "Kb" )
# [1] "65.3 Kb"
``

I still need to add some tests and updated the docs, but I think this will solve the large object size for you?

**Comment by SymbolixAU** [comment]
now in master

**Comment by tim-salabim** [comment]
yes, this solves the issue. Thanks! Feel free to close (I would but don't know if you still need to update tests etc).
