### ISSUE TITLE
downcast

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/geojsonsf#53]
MULTI* geometries into their simpler forms

TODO - sf
- [x] MULTIPOINT -> POINT
- [x] MULTILINESTRING -> LINESTRING
- [x] MULTIPOLYGON -> POLYGON

atomising is tricker; need to expand the `Rcpp::StringVector` according to the number of down-cast geometries in each iteration. Could be expensive. 

TODO sf-atomise
- [ ] MULTIPOINT -> POINT
- [ ] MULTILINESTRING -> LINESTRING
- [ ] MULTIPOLYGON -> POLYGON

**Comment by dcooley** [comment]
can now use `sfheaders` for this.
