### ISSUE TITLE
Adding a GitHub URL to DESCRIPTION

### ISSUE THREAD

**Issue by lorenzwalthert** [SymbolixAU/geojsonsf#69]
Currently, there is no link from the [CRAN](https://cran.r-project.org/web/packages/geojsonsf/index.html) page to GitHub. Simply adding an URL and Bugs field to the DESCRIPTION would help. LIke [here](https://github.com/r-lib/styler/blob/master/DESCRIPTION#L17-L18).

**Comment by dcooley** [comment]
done. Thanks.
