### ISSUE TITLE
Not picking up CRS when serializing?

### ISSUE THREAD

**Issue by lorenzwalthert** [SymbolixAU/geojsonsf#70]
According to a [highly upvoted Stackoverflow answer](https://gis.stackexchange.com/questions/60928/how-to-insert-a-geojson-polygon-into-a-postgis-table), the way to specify the CRS in a GeoJSON is like this: 
```json
{
    "type":"Polygon",
    "coordinates":
    [
        [
            [-91.23046875,45.460130637921],
            [-79.8046875,49.837982453085],
            [-69.08203125,43.452918893555],
            [-88.2421875,32.694865977875],
            [-91.23046875,45.460130637921]
        ]
    ],
    "crs":{"type":"name","properties":{"name":"EPSG:3857"}}
}

```

Unfortunately, it does not seem to be recognized: 

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3
geojsonsf::geojson_sfc('{
    "type":"Polygon",
    "coordinates":
    [
        [
            [-91.23046875,45.460130637921],
            [-79.8046875,49.837982453085],
            [-69.08203125,43.452918893555],
            [-88.2421875,32.694865977875],
            [-91.23046875,45.460130637921]
        ]
    ],
    "crs":{"type":"name","properties":{"name":"EPSG:3857"}}
}')
#> Geometry set for 1 feature 
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: -91.23047 ymin: 32.69487 xmax: -69.08203 ymax: 49.83798
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#> POLYGON ((-91.23047 45.46013, -79.80469 49.8379...
```

<sup>Created on 2019-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

What am I missing? I currently use `sf::st_set_crs()` to set it later manually, but this is hacky and dangerous in general I think.

**Comment by dcooley** [comment]
as per [RFC 7946](https://tools.ietf.org/html/rfc7946#section-4) 

> The coordinate reference system for all GeoJSON coordinates is a
   geographic coordinate reference system, using the World Geodetic
   System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units
   of decimal degrees.  This is equivalent to the coordinate reference
   system identified by the Open Geospatial Consortium (OGC) URN
   urn:ogc:def:crs:OGC::CRS84

And in [Appendix B](https://tools.ietf.org/html/rfc7946#appendix-B)

> Specification of coordinate reference systems has been removed,  i.e., the "crs" member of [GJ2008] is no longer used.

So I haven't supported using other CRS values

**Comment by lorenzwalthert** [comment]
Ok, thanks. So do you think a warning for that case would be appropriate? Because the way I understand your answer, it's technically wrong to use a different CRS in the GeoJSON than WGS84? This feels quite strict. I suppose in this case, the workaround would be to parse the CRS myself from the geojson and then anyways use `sf::st_set_crs()`.

**Comment by dcooley** [comment]
> it's technically wrong to use a different CRS in the GeoJSON than WGS84?

This is my understanding too, but, I'm happy to be corrected. 

I think a warning is a good idea; I'll see if I can implement it without any performance cost, otherwise the simplest solution would be a more explicit documentation.

**Comment by lorenzwalthert** [comment]
Sounds good.

**Comment by dcooley** [comment]
Although, if it's as simple as I suspect it might be I'm left with the dilemma -

if a user has supplied a crs, should I include it anyway and ignore the RFC?

**Comment by lorenzwalthert** [comment]
Depends on how strict you want to adhere to the standard, but usually you can either comply or not comply. I am not familiar with the domain. An alternative would be to allow the user to specify the CRS via a separate argument in `geojsonsf::geojson_sfc()`, so the returned sfc object would have the correct CRS set already.

**Comment by dcooley** [comment]
That actually might be a better idea. I'll have a sleep on it and try a couple of approaches tomorrow.

**Comment by SymbolixAU** [comment]
I've made a branch where I've added `crs` and `proj4string` fields to `geojson_sfc()` and `geojson_sf()`, and updated the documentation accordingly

```r
devtools::install_github("SymbolixAu/geojsonsf", ref = "issue70")
```

Could you install this version and let me know if it works, and is a suitable update for you?

**Comment by lorenzwalthert** [comment]
Thanks a lot. Unfortuntately, I did not have a chance to test your solution. I believe the [added NEWS bullet](https://github.com/SymbolixAU/geojsonsf/commit/607772b894b53c09c4a2f779652517d90e1a9abb#diff-8312ad0561ef661716b48d09478362f3R4) misses a word.

**Comment by dcooley** [comment]
thanks - fixed.

**Comment by lorenzwalthert** [comment]
I have tested this now. However, since you depricated `crs`, I believe I have to specify a WKT now that is very cumbersome. Can't you derive this from the CRS?


``` r
x <- 604819.46
y <- 193245.34
sfc <- sf::st_sfc(sf::st_point(c(x, y)), crs = 2056)
json <- geojsonsf::sfc_geojson(sfc) # should proabably also warn / fail on non WGS84

geojsonsf::geojson_sf(json, crs = 2056) # CRS ignored, so I have to use WKT. How does it look like?
#> Warning in set_crs(sf[["geometry"]], input, wkt, crs, proj4string): crs and
#> proj4string are deprecated. Please now use input and wkt
#> Simple feature collection with 1 feature and 0 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 604819.5 ymin: 193245.3 xmax: 604819.5 ymax: 193245.3
#> z_range:        zmin: NA zmax: NA
#> m_range:        mmin: NA mmax: NA
#> CRS:            4326
#>                    geometry
#> 1 POINT (604819.5 193245.3)

crs <- sf::st_crs(sfc)
crs$wkt
#> [1] "PROJCS[\"CH1903+ / LV95\",\n    GEOGCS[\"CH1903+\",\n        DATUM[\"CH1903+\",\n            SPHEROID[\"Bessel 1841\",6377397.155,299.1528128,\n                AUTHORITY[\"EPSG\",\"7004\"]],\n            TOWGS84[674.374,15.056,405.346,0,0,0,0],\n            AUTHORITY[\"EPSG\",\"6150\"]],\n        PRIMEM[\"Greenwich\",0,\n            AUTHORITY[\"EPSG\",\"8901\"]],\n        UNIT[\"degree\",0.0174532925199433,\n            AUTHORITY[\"EPSG\",\"9122\"]],\n        AUTHORITY[\"EPSG\",\"4150\"]],\n    PROJECTION[\"Hotine_Oblique_Mercator_Azimuth_Center\"],\n    PARAMETER[\"latitude_of_center\",46.95240555555556],\n    PARAMETER[\"longitude_of_center\",7.439583333333333],\n    PARAMETER[\"azimuth\",90],\n    PARAMETER[\"rectified_grid_angle\",90],\n    PARAMETER[\"scale_factor\",1],\n    PARAMETER[\"false_easting\",2600000],\n    PARAMETER[\"false_northing\",1200000],\n    UNIT[\"metre\",1,\n        AUTHORITY[\"EPSG\",\"9001\"]],\n    AXIS[\"Easting\",EAST],\n    AXIS[\"Northing\",NORTH],\n    AUTHORITY[\"EPSG\",\"2056\"]]"
```

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dcooley** [comment]
> Can't you derive this from the CRS?

No. 

> Or are there helper functions I could use

Yes, in `library(sf)` you can `sf::st_transform()` between CRS.
