### ISSUE TITLE
Only properties and geometry objects

### ISSUE THREAD

**Issue by layik** [SymbolixAU/geojsonsf#76]
Hi @SymbolixAU, find myself using the great package again, this time for [`geocoder`](https://github.com/layik/geocoder) which you might find interesting but will keep that discussion off the ticket. 

I hope this is an improvement ticket: could we set a switch in the cpp code to just return the "features" without the "featurecollection" and "types" of the "features" in [`sf_geojson`](https://github.com/SymbolixAU/geojsonsf/blob/master/R/sf_geojson.R#L36)`?

So instead of:
```
{"type":"FeatureCollection","features":[
  {"type":"Feature","properties":{"id":1.0},"geometry":{"type":"Point","coordinates":[0.0,0.0]}},
  {"type":"Feature","properties":{"id":2.0},"geometry":{"type":"Point","coordinates":[0.0,0.0]}}
]}
```
we get a valid json:
```
{
 "properties":{"id":1.0},"geometry":{"type":"Point","coordinates":[0.0,0.0]},
  "properties":{"id":2.0},"geometry":{"type":"Point","coordinates":[0.0,0.0]}
}
```

Please ignore me and close if you think I should just handle the output of `sf_geojson` myself or do this entirely differently.

If we agree, I might just spend the time on a PR here.

**Comment by dcooley** [comment]
Currently it's possible to use `atomise = TRUE` to remove the `FeatureCollection` type

```r
geojsonsf::sf_geojson( sf, atomise = TRUE )
# {"type":"Feature","properties":{"id":1.0},"geometry":{"type":"Point","coordinates":[0.0,0.0]}} 
# {"type":"Feature","properties":{"id":2.0},"geometry":{"type":"Point","coordinates":[0.0,0.0]}}
```

Can you use this, or do you want to remove the `"type":"Feature"` as well?

**Comment by layik** [comment]
That is great @dcooley. Considering reconstruction of the GeoJSON object, that might be the right way of doing it. This is my best so far:

```r
by(v, 1:nrow(v), function(x){
  #' unboxed properties
  jl = jsonify::to_json(st_drop_geometry(x))
  jl = substring(text = jl, 2, nchar(jl) - 1)
  json = paste0(
  '{"properties": ', jl, ',',
    '"geometry": ', geojsonsf::sfc_geojson(st_geometry(x)),'}'
  )
  stopifnot(jsonify::validate_json(json))
  mongo$insert(json)
})
```

I will close the ticket as I think `atomise` is the same.

**Comment by dcooley** [comment]
yes it looks like `atomise` is what you're after - I added this argument specifically for getting the GeoJSON into the right format for inserting into MongoDB.
