### ISSUE TITLE
geojsonsf::geojson_sf add NA_character_ in "input" field of "crs" which make the object unusable by sf package

### ISSUE THREAD

**Issue by etiennekintzler** [SymbolixAU/geojsonsf#83]
I am using:
- geojsonsf version 1.3.3 
- sf version  0.8-1
- R version 3.6.3 (2020-02-29)
- os Ubuntu 18.04.4 LTS.

Below is a minimal example:

```R
geojson <- '{ "type" : "Point", "coordinates" : [0, 0] }'
sf_obj <- geojsonsf::geojson_sf(geojson) 
sf::st_is_valid(sf_obj)
```

yields the following error : 
```R
Error in CPL_geos_is_valid(x[i], as.logical(NA_on_exception)) : 
  Not compatible with requested type: [type=character; target=integer].
```

Digging down and comparing the dput with a functional one (from `sf::read_sf`) showed that the issue is that the call to `_geojsonsf_rcpp_read_sf_file` add **two fields "input" and "wkt" to the "crs" attributes in the "geometry" with values `NA_character_`  while (according to what I understood from the error) it should be `NA_integer_`**.

Replacing `NA_character_` with `NA_integer_` solve the issue: 

```R
attr(sf_obj$geometry, "crs")$input <- NA_integer_
sf::st_is_valid(sf_obj) # OK now
```

The error also vanish when importing with default `crs` option such as `sf_obj <- geojsonsf::geojson_sf(geojson, crs=4326)` since no fields "input" and "wkt" are created in crs attributes (and then no inappropriate `NA_character_` values).

**Comment by dcooley** [comment]
Thanks for reporting this. However, there's a couple of things going on here, notably with the update to `sf` from v0.9, where the `crs` object is [changing](https://www.r-spatial.org/r/2020/03/17/wkt.html#crs-objects-in-sf)

> Pre-0.9 versions of sf used crs (coordinate reference system) objects represented as lists with two components, epsg (possibly set as NA) and proj4string:

> now, with sf >= 0.9, crs objects are lists with two components, input and wkt:

---

So I'm updating `geojsonsf` to align with `sf` v0.9, where I think have I have this issue fixed.

Could you you do me a favour and test the latest dev version of `geojsonsf` using your current `sf`  0.8-1?

```r
remotes::install_github("SymbolixAU/geojsonsf")
```

And tell me if you still get this error?

**Comment by etiennekintzler** [comment]
I just tried the exact same code now get the following error : 

```R
Error: C stack usage  7970148 is too close to the limit
```

As you mentioned using a `sf`  version over 0.9 solves the problem.

**Comment by etiennekintzler** [comment]
For you information the C stack usage error persists even after installing the last version d845e12f850aecf9904732aa89746727770da868 (using sf 0.8-1 ofc)

**Comment by dcooley** [comment]
I'm adding an `onAttach` message to warn about the conflict between versions - https://github.com/SymbolixAU/geojsonsf/blob/master/R/onAttach.R

**Comment by etiennekintzler** [comment]
Ok but why not make the package handle both version of `sf` ? Does it incurs more work than just fixing the attributes types in crs ?

Also the C stack usage error persists on the new version.
