### ISSUE TITLE
reduce R dependency

### ISSUE THREAD

**Issue by dcooley** [SymbolixAU/geojsonsf#87]
https://github.com/SymbolixAU/geojsonsf/commit/d845e12f850aecf9904732aa89746727770da868#r40817978

@layik - I'll have a look at what it will take. I remember it error-ing during the last submission, but I'll see if I can reduce it for the next update in a couple of days

**Comment by dcooley** [comment]
The latest version on master branch is reduced to `R >=3.3.0`

**Comment by layik** [comment]
Thanks @dcooley I m sure it will help some folks. Good to be backward compatible.
