### ISSUE TITLE
Invlaid JSON error on ArcGIS geojson API

### ISSUE THREAD

**Issue by plnnr** [SymbolixAU/geojsonsf#88]
When I try to convert JSON from an ArcGIS API ([here](https://gis-pdx.opendata.arcgis.com/datasets/neighborhoods-regions)) using the code below:

`portland_neighborhoods <- geojson_sf(readLines("https://opendata.arcgis.com/datasets/9f50a605cf4945259b983fa35c993fe9_125.geojson"))`

I get the following error:
`Error in rcpp_geojson_to_sf(geojson, expand_geometries) : Invalid JSON`

I tried following the advice from #16, having downloaded the raw file and pasting the contents into a geojson linter. The error is that the geojson text shouldn't specify a CRS if it is the default CRS (`Invalid GeoJSON. Line 1: old-style crs member is not recommended, this object is equivalent to the default and should be removed`). However, given that this is coming from an ArcGIS open data platform, the fact that it specifies the default CRS should be ignored, instead of terminating in error. Any way to get around this?

I have tried this with other geojson datasets in the [Open Data portal](https://gis-pdx.opendata.arcgis.com), and it results in the same error.

**Comment by dcooley** [comment]
I think you're issue is coming from `readLines`, which is reading the text as separate lines. If you ignore that, `geojson_sf()` can read directly from a URL.

This works

```r
library(sf) ## for the nice print method
geojsonsf::geojson_sf("https://opendata.arcgis.com/datasets/9f50a605cf4945259b983fa35c993fe9_125.geojson")
```

**Comment by plnnr** [comment]
Thank you!

> I think you're issue is coming from `readLines`, which is reading the text as separate lines. If you remove that, `geojson_sf()` can read directly from a URL.
> 
> This works
> 
> ```r
> library(sf) ## for the nice print method
> geojsonsf::geojson_sf("https://opendata.arcgis.com/datasets/9f50a605cf4945259b983fa35c993fe9_125.geojson")
> ```
