### ISSUE TITLE
geojson_wkt fails when applied to certain GeoJSON objects

### ISSUE THREAD

**Issue by megaraptor1** [SymbolixAU/geojsonsf#98]
When trying to convert data for the Conemaugh Formation from macrostrat into a stratigraphic map following the protocol on [this page](https://www.benlinzmeier.rocks/post/making-a-geological-map-with-macrostrat-and-ggplot/), I get the error message "Error: Invalid JSON" when trying to convert the JSON into WKT format.

Having talked with the author of that page we found the code failed when `geojson_wkt()` was called. Below is code that replicates the error.

```
library(RCurl)
library(tidyverse)
library(sf)
library(ggspatial)
library(rnaturalearth)
library(rnaturalearthdata)
library(geojsonsf)
sf_use_s2(FALSE)

y_conemaugh <- getURL("https://macrostrat.org/api/v2/geologic_units/map?strat_name_id=2439&format=geojson_bare",
                      .opts = curlOptions(ssl.verifypeer=FALSE, verbose=TRUE))
sf_temp_conemaugh <- geojson_wkt(y_conemaugh)
```

Notably, this happens only with the JSON for the Conemaugh Formation. The same code works when tried with various other formations (see below for examples).

```
y1 <- getURL("https://macrostrat.org/api/v2/geologic_units/map?strat_name_id=1351&format=geojson_bare",
            .opts = curlOptions(ssl.verifypeer=FALSE, verbose=TRUE))
y2 <- getURL("https://macrostrat.org/api/v2/geologic_units/map?strat_name_id=867&format=geojson_bare",
            .opts = curlOptions(ssl.verifypeer=FALSE, verbose=TRUE))
y3 <- getURL("https://macrostrat.org/api/v2/geologic_units/map?strat_name_id=4174&format=geojson_bare",
            .opts = curlOptions(ssl.verifypeer=FALSE, verbose=TRUE))

sf_temp_1 <- geojson_wkt(y1)
sf_temp_2 <- geojson_wkt(y2)
sf_temp_3 <- geojson_wkt(y3)
```

Neither myself nor the author of the linked page can figure out exactly why `geojson_wkt()` works with some JSONs for stratigraphic formations, but not with others, and it was suggested I post a new issue here.

**Comment by dcooley** [comment]
`y_conemaugh` is a string of html tags. Is this really what it should be?

```
y_conemaugh
[1] "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```

**Comment by megaraptor1** [comment]
I think so. I checked the other "y" objects that are supposed to be geoJSON objects and they looked the same.

**Comment by dcooley** [comment]
That string of html tagas will _never_ work, it's not valid geojson

**Comment by megaraptor1** [comment]
Okay, thank you for letting me know, I will check to see if there is an issue on the other end.
