### ISSUE TITLE
Dependencies 'geometries' and 'sfheaders' require C++ 17?

### ISSUE THREAD

**Issue by clozanoruiz** [SymbolixAU/geojsonsf#99]
Hi,
I am on R 3.6 (on Windows) and just tried to update all packages RStudio lists as updatable. Among them where a few dependencies for geojsonsf: geometries and sfheaders.
However, when updating hey throw an error regarding some system requirements for C++ 17. I have Rtools35, which apparently is the recommended version for building R packages between R3.5 and 3.6, and I guess that toolchain doesn't support C++17 (I have no clue in C++ programming)?

Is C++ 17 really required to build those two dependencies? I guess could fork those packages, remove CXX_STD=CXX11 from Makevars*, and also the SystemRequirements line from the DESCRIPTION file and try to build them but I wanted first to check with you in case there is something else and the packages really require C++17.

Thanks.

**Comment by dcooley** [comment]
Thanks for the question.

> Is C++ 17 really required 

you know what, I'm not sure.. But a few weeks ago I got an email from CRAN saying their minimum supported version is gong to be C++17, so I changed it to this, otherwise they were going to remove the packages.

But as a test I've set up branches on both packages without this requirement. Could you install these, then `geojsonsf` and le tme know if it works for you. 

```r
remotes::install_github("dcooley/geometries", ref = "issue18")
remotes::install_github("dcooley/sfheaders", ref = "issue97")
remotes::install_github("SymbolixAU/geojsonsf")
```

**Comment by clozanoruiz** [comment]
Thanks for looking into this. However, I will be back to my desk on Tuesday and I won't be able to try what you suggest till then. I will let you know the results.
________________________________

**Comment by clozanoruiz** [comment]
> Could you install these, then `geojsonsf` and le tme know if it works for you.

Hi,
Yes. it worked. I was able to install them and use them without aparrently any errors. Now, I don´t know what you should do, either remove the SystemRequiremts stuff or not... ?
However, here (https://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file) it is suggested that SystemRequirements should be used to specify non-default C++ standard, which I would understand it is not needed unless a specific C++ version is required?
 But, again, I have no idea of C++ and what needs to be done when using it on R packages.

Thanks, for your help.

**Comment by ateucher** [comment]
I wrote up a bit about the changes at CRAN regarding C++ standard specification [here](https://www.tidyverse.org/blog/2023/03/cran-checks-compiled-code/#note-regarding-systemrequirements-c11). But essentially they are saying don't specify anything unless you know a certain standard is required.

**Comment by dcooley** [comment]
Thanks @ateucher for the article. I'm now removing the C++ requirements from these three pacakges and they should hopefully be updated on CRAN in the next few days.

**Comment by dcooley** [comment]
{sfheaders} and {geometrie} are accepted on CRAN, and {geojsonsf} is on its way

**Comment by dcooley** [comment]
actually, geojsonsf needs C++ 11, so that's staying as-is.
